GOOGLE_API_KEY = "AIzaSyBD9MWNN7Ntu32w_E_6EDQygvyJwQS-n6c"

# --- Database Credentials (replace with your actual values) ---
MYSQL_USER="adit"     
MYSQL_PASSWORD="yourpassword"
MYSQL_HOST="localhost"
MYSQL_PORT="3306"                 
MYSQL_DATABASE="mychinook"